### ISSUE TITLE
This is an awesome plugin

### ISSUE THREAD

**Issue by JerryLan2** [liammagee/obsidian-topic-linking#6]
Hi @liammagee ,
I think your plugin is awesome and I have only tried the extract PDFs!  And I have not come to the other 2 functions yet which by the sound of it sounds great. I delayed trying your plugin because of the caveat that its experimental plugin. When I tried, it worked. When your plugin is out of Beta, I think it will be very popular.

Unfortunately recently it stopped working and only an emptey image folder is created. Have I done something differently in setting the path address? More likely I think its because the plugin is not updated to the latest obsidian version. I downgraded two obsidian versions down but your plugin still does not work. Is there a workaround to get your plugin to work until the issue is resolved? not urgent but I am itching to use it with excalibrain and breadcrumb. I need the pdf files into md format so that I can create links. Thanks for the great work!

Cheers,
Jerry

**Comment by liammagee** [comment]
Thanks for the feedback and comments. I’ll look into compatibility issues with 0.16 and post a patch this week.

**Comment by liammagee** [comment]
Hi,

Just following this up - I can't seem to reproduce the issue, as the plugin still works well for me on 0.16.2 .

Would you mind sending me a sample of the PDFs you're looking to convert? Or perhaps look at the Developer Tools output (accessible via View | Toggle Developer Tools)?

Liam.

**Comment by JerryLan2** [comment]
Hi Liam,
I tried on the same pdf which worked before. I cannot find View | Toggle Developer Tools. Thanks for guidance!

only a blank image folder is produced
![image](https://user-images.githubusercontent.com/101081188/189127177-851a7685-1ca6-4d9d-a656-d6a8946e517b.png)

I have put 3 pdfs into:
![image](https://user-images.githubusercontent.com/101081188/189127576-5828be33-331e-4d72-9cee-e75437ba0605.png)


Jerry

**Comment by liammagee** [comment]
Thanks Jerry. If they're not too sensitive would you mind uploading them
here?

Liam.

**Comment by JerryLan2** [comment]
[william_shakespeare_2012_1.pdf](https://github.com/liammagee/obsidian-topic-linking/files/9534482/william_shakespeare_2012_1.pdf)

[Alices-Adventures-in-Wonderland.pdf](https://github.com/liammagee/obsidian-topic-linking/files/9534490/Alices-Adventures-in-Wonderland.pdf)

Hi Liam,
I tried with a random pdf from the web. At first, it says "Generating markdown.." . It was taking longer than last time and since not even the Generated2 folder was created, I closed obsidian. I did again but this time when I run the command "Extract pdf", nothing happens.

I also note that tranclude images which was under experimental is not there  anymore. This also was working previously.

Regards,
Jerry

**Comment by liammagee** [comment]
Thanks again. Both files appear to be working for me. I've pushed another release that addresses other minor spacing issues. If you update the plugin, this problem will hopefully have gone away. But happy to look at it further if it persists.

[Alices-Adventures-in-Wonderland.md](https://github.com/liammagee/obsidian-topic-linking/files/9545232/Alices-Adventures-in-Wonderland.md)
[william_shakespeare_2012_1.md](https://github.com/liammagee/obsidian-topic-linking/files/9545233/william_shakespeare_2012_1.md)

**Comment by JerryLan2** [comment]
Hi Liam,

How are you? I updated the plugin but still same.

![image](https://user-images.githubusercontent.com/101081188/190071500-2a3a0d34-72db-4f69-ba2a-cbb56921863c.png)


From the picture, anything wrong?

**Comment by liammagee** [comment]
Hi Jerry,

Ah, it might be the case that you're not creating the 'Generated2' folder first? The plugin won't create this folder, only emit Markdown files when the folder is already there.

So just to confirm, you'll want to have (for this structure to work):

PDFS2/ [with some PDF files in it]
Generated2/ 

Both inside the vault where the plugin is installed.

If that doesn't work, I might try to coordinate a email or Zoom exchange, to get to the bottom of it. 

Liam.

**Comment by JerryLan2** [comment]
Hi Liam,

I confirm that there are PDF files in folder PDFS2 which is also under root directory. Also confirm that there is already a folder named "Generated2" under root directory. I tried twice, yesterday and today, but its still not working. Thanks Liam!

Rgds,
Jerry

**Comment by liammagee** [comment]
Hi Jerry,

The screenshot shows 'PDFS2' - your message says 'PDFS'. Could you check
that these match exactly?

Liam.

**Comment by JerryLan2** [comment]
Hi Liam,

Yes its PDFS2. I edited the typo but it was reflected too late.

Jerry

**Comment by JerryLan2** [comment]
> Hi Jerry,
> 
> Ah, it might be the case that you're not creating the 'Generated2' folder first? The plugin won't create this folder, only emit Markdown files when the folder is already there.
> 
> So just to confirm, you'll want to have (for this structure to work):
> 
> PDFS2/ [with some PDF files in it] Generated2/
> 
> Both inside the vault where the plugin is installed.
> 
> If that doesn't work, I might try to coordinate a email or Zoom exchange, to get to the bottom of it.
> 
> Liam.

Hi Liam,

Good Day!! I have a temporary email you can reach me at: lauj12846@gmail.com if you are willing to arrange for the zoom meet.

Cheers
Jerry
